# Generated by Django 5.2.1 on 2025-06-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='reward',
            table='Reward',
        ),
        migrations.AlterModelTable(
            name='rewardapplication',
            table='RewardApplication',
        ),
    ]
