# Generated by Django 5.2.1 on 2025-06-07 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewardapp', '0003_reward_receiver_alter_reward_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='rewardapp.category'),
        ),
    ]
