# Generated by Django 5.2.1 on 2025-06-07 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewardapp', '0004_alter_reward_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='rewardapp.category'),
        ),
    ]
