# Generated by Django 5.2.1 on 2025-06-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewardapp', '0005_alter_reward_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('payed', 'Payed'), ('callback', 'Callback'), ('cancelled', 'Cancelled'), ('teke_down', 'TakeDown')], default='waiting', max_length=20),
        ),
    ]
